package com.toolshare.entity;

public enum NotificationType {
    BORROW_APPROVED,
    BORROW_REJECTED,
    BORROW_RETURNED,
    BORROW_OVERDUE,
    BORROW_OVERDUE_REMINDER,
    BORROW_DUE_SOON,
    NEW_BORROW_REQUEST,
    MAINTENANCE_DUE,
    MAINTENANCE_DUE_SOON,
    MAINTENANCE_COMPLETED
}
